name: test-env
channels:
  - defaults
dependencies:
  - alabaster=0.7.12=pyhd3eb1b0_0
  - arrow=1.2.3=py311haa95532_1
  - astroid=2.14.2=py311haa95532_0
  - asttokens=2.0.5=pyhd3eb1b0_0
  - atomicwrites=1.4.0=py_0
  - attrs=23.1.0=py311haa95532_0
  - autopep8=1.6.0=pyhd3eb1b0_1
  - babel=2.11.0=py311haa95532_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - bcrypt=3.2.0=py311h2bbff1b_1
  - beautifulsoup4=4.12.2=py311haa95532_0
  - binaryornot=0.4.4=pyhd3eb1b0_1
  - black=23.11.0=py311haa95532_0
  - bleach=4.1.0=pyhd3eb1b0_0
  - brotli-python=1.0.9=py311hd77b12b_7
  - bzip2=1.0.8=he774522_0
  - ca-certificates=2023.08.22=haa95532_0
  - certifi=2023.11.17=py311haa95532_0
  - cffi=1.16.0=py311h2bbff1b_0
  - chardet=4.0.0=py311haa95532_1003
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - click=8.1.7=py311haa95532_0
  - cloudpickle=2.2.1=py311haa95532_0
  - colorama=0.4.6=py311haa95532_0
  - comm=0.1.2=py311haa95532_0
  - cookiecutter=2.5.0=py311haa95532_0
  - cryptography=41.0.7=py311h89fc84f_0
  - debugpy=1.6.7=py311hd77b12b_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - diff-match-patch=20200713=pyhd3eb1b0_0
  - dill=0.3.7=py311haa95532_0
  - docstring-to-markdown=0.11=py311haa95532_0
  - docutils=0.18.1=py311haa95532_3
  - executing=0.8.3=pyhd3eb1b0_0
  - flake8=6.0.0=py311haa95532_0
  - icu=73.1=h6c2663c_0
  - idna=3.4=py311haa95532_0
  - imagesize=1.4.1=py311haa95532_0
  - importlib-metadata=6.0.0=py311haa95532_0
  - importlib_metadata=6.0.0=hd3eb1b0_0
  - inflection=0.5.1=py311haa95532_0
  - intervaltree=3.1.0=pyhd3eb1b0_0
  - ipykernel=6.25.0=py311h746a85d_0
  - ipython=8.15.0=py311haa95532_0
  - ipython_genutils=0.2.0=pyhd3eb1b0_1
  - isort=5.9.3=pyhd3eb1b0_0
  - jaraco.classes=3.2.1=pyhd3eb1b0_0
  - jedi=0.18.1=py311haa95532_1
  - jellyfish=1.0.1=py311h36a85e1_0
  - jinja2=3.1.2=py311haa95532_0
  - jpeg=9e=h2bbff1b_1
  - jsonschema=4.19.2=py311haa95532_0
  - jsonschema-specifications=2023.7.1=py311haa95532_0
  - jupyter_client=8.6.0=py311haa95532_0
  - jupyter_core=5.5.0=py311haa95532_0
  - jupyterlab_pygments=0.2.2=py311haa95532_0
  - keyring=23.13.1=py311haa95532_0
  - krb5=1.20.1=h5b6d351_0
  - lazy-object-proxy=1.6.0=py311h2bbff1b_0
  - libclang=14.0.6=default_hb5a9fac_1
  - libclang13=14.0.6=default_h8e68704_1
  - libffi=3.4.4=hd77b12b_0
  - libpng=1.6.39=h8cc25b3_0
  - libpq=12.15=h906ac69_1
  - libsodium=1.0.18=h62dcd97_0
  - libspatialindex=1.9.3=h6c2663c_0
  - lz4-c=1.9.4=h2bbff1b_0
  - markdown-it-py=2.2.0=py311haa95532_1
  - markupsafe=2.1.1=py311h2bbff1b_0
  - matplotlib-inline=0.1.6=py311haa95532_0
  - mccabe=0.7.0=pyhd3eb1b0_0
  - mdurl=0.1.0=py311haa95532_0
  - mistune=2.0.4=py311haa95532_0
  - more-itertools=10.1.0=py311haa95532_0
  - mypy_extensions=1.0.0=py311haa95532_0
  - nbclient=0.8.0=py311haa95532_0
  - nbconvert=7.10.0=py311haa95532_0
  - nbformat=5.9.2=py311haa95532_0
  - nest-asyncio=1.5.6=py311haa95532_0
  - numpydoc=1.5.0=py311haa95532_0
  - openssl=3.0.12=h2bbff1b_0
  - packaging=23.1=py311haa95532_0
  - pandocfilters=1.5.0=pyhd3eb1b0_0
  - paramiko=2.8.1=pyhd3eb1b0_0
  - parso=0.8.3=pyhd3eb1b0_0
  - pathspec=0.10.3=py311haa95532_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pip=23.3.1=py311haa95532_0
  - platformdirs=3.10.0=py311haa95532_0
  - pluggy=1.0.0=py311haa95532_1
  - ply=3.11=py311haa95532_0
  - prompt-toolkit=3.0.36=py311haa95532_0
  - psutil=5.9.0=py311h2bbff1b_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pycodestyle=2.10.0=py311haa95532_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pydocstyle=6.3.0=py311haa95532_0
  - pyflakes=3.0.1=py311haa95532_0
  - pygments=2.15.1=py311haa95532_1
  - pylint=2.16.2=py311haa95532_0
  - pylint-venv=2.3.0=py311haa95532_0
  - pyls-spyder=0.4.0=pyhd3eb1b0_0
  - pynacl=1.5.0=py311h8cc25b3_0
  - pyopenssl=23.2.0=py311haa95532_0
  - pyqt=5.15.10=py311hd77b12b_0
  - pyqt5-sip=12.13.0=py311h2bbff1b_0
  - pyqtwebengine=5.15.10=py311hd77b12b_0
  - pysocks=1.7.1=py311haa95532_0
  - python=3.11.5=he1021f5_0
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python-fastjsonschema=2.16.2=py311haa95532_0
  - python-lsp-black=1.2.1=py311haa95532_0
  - python-lsp-jsonrpc=1.0.0=pyhd3eb1b0_0
  - python-lsp-server=1.7.2=py311haa95532_0
  - python-slugify=5.0.2=pyhd3eb1b0_0
  - pytoolconfig=1.2.6=py311haa95532_0
  - pytz=2023.3.post1=py311haa95532_0
  - pywin32=305=py311h2bbff1b_0
  - pywin32-ctypes=0.2.0=py311haa95532_1000
  - pyyaml=6.0.1=py311h2bbff1b_0
  - pyzmq=25.1.0=py311hd77b12b_0
  - qdarkstyle=3.0.2=pyhd3eb1b0_0
  - qstylizer=0.2.2=py311haa95532_0
  - qt-main=5.15.2=h19c9488_10
  - qt-webengine=5.15.9=h5bd16bc_7
  - qtawesome=1.2.2=py311haa95532_0
  - qtconsole=5.4.2=py311haa95532_0
  - qtpy=2.4.1=py311haa95532_0
  - referencing=0.30.2=py311haa95532_0
  - requests=2.31.0=py311haa95532_0
  - rich=13.3.5=py311haa95532_0
  - rope=1.7.0=py311haa95532_0
  - rpds-py=0.10.6=py311h062c2fa_0
  - rtree=1.0.1=py311h2eaa2aa_0
  - setuptools=68.0.0=py311haa95532_0
  - sip=6.7.12=py311hd77b12b_0
  - six=1.16.0=pyhd3eb1b0_1
  - snowballstemmer=2.2.0=pyhd3eb1b0_0
  - sortedcontainers=2.4.0=pyhd3eb1b0_0
  - soupsieve=2.5=py311haa95532_0
  - sphinx=5.0.2=py311haa95532_0
  - sphinxcontrib-applehelp=1.0.2=pyhd3eb1b0_0
  - sphinxcontrib-devhelp=1.0.2=pyhd3eb1b0_0
  - sphinxcontrib-htmlhelp=2.0.0=pyhd3eb1b0_0
  - sphinxcontrib-jsmath=1.0.1=pyhd3eb1b0_0
  - sphinxcontrib-qthelp=1.0.3=pyhd3eb1b0_0
  - sphinxcontrib-serializinghtml=1.1.5=pyhd3eb1b0_0
  - spyder=5.4.3=py311haa95532_1
  - spyder-kernels=2.4.4=py311haa95532_0
  - sqlite=3.41.2=h2bbff1b_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - text-unidecode=1.3=pyhd3eb1b0_0
  - textdistance=4.2.1=pyhd3eb1b0_0
  - three-merge=0.1.1=pyhd3eb1b0_0
  - tinycss2=1.2.1=py311haa95532_0
  - tk=8.6.12=h2bbff1b_0
  - toml=0.10.2=pyhd3eb1b0_0
  - tomlkit=0.11.1=py311haa95532_0
  - tornado=6.3.3=py311h2bbff1b_0
  - traitlets=5.7.1=py311haa95532_0
  - ujson=5.4.0=py311hd77b12b_0
  - unidecode=1.2.0=pyhd3eb1b0_0
  - urllib3=1.26.18=py311haa95532_0
  - vc=14.2=h21ff451_1
  - vs2015_runtime=14.27.29016=h5e58377_2
  - watchdog=2.1.6=py311haa95532_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - webencodings=0.5.1=py311haa95532_1
  - whatthepatch=1.0.2=py311haa95532_0
  - wheel=0.41.2=py311haa95532_0
  - win_inet_pton=1.1.0=py311haa95532_0
  - wrapt=1.14.1=py311h2bbff1b_0
  - xz=5.4.5=h8cc25b3_0
  - yaml=0.2.5=he774522_0
  - yapf=0.31.0=pyhd3eb1b0_0
  - zeromq=4.3.4=hd77b12b_0
  - zipp=3.11.0=py311haa95532_0
  - zlib=1.2.13=h8cc25b3_0
  - zstd=1.5.5=hd43e919_0
  - pip:
      - aiosignal==1.3.1
      - contourpy==1.2.0
      - cycler==0.12.1
      - filelock==3.13.1
      - fonttools==4.46.0
      - frozenlist==1.4.0
      - joblib==1.3.2
      - kiwisolver==1.4.5
      - llvmlite==0.41.1
      - matplotlib==3.8.2
      - mpmath==1.3.0
      - msgpack==1.0.7
      - numba==0.58.1
      - numpy==1.26.2
      - pandas==2.1.4
      - pillow==10.1.0
      - protobuf==4.25.1
      - pyparsing==3.1.1
      - ray==2.8.1
      - scikit-learn==1.3.2
      - scipy==1.11.4
      - sympy==1.12
      - threadpoolctl==3.2.0
      - tzdata==2023.3
prefix: C:\Users\P1UAnapaula.Arme\AppData\Local\miniconda3\envs\test-env
